/**
 * adminAuthController.js — Handlers for admin authentication endpoints
 *
 * POST /api/admin/login   → validate credentials, issue custom JWT + Supabase session
 * POST /api/admin/logout  → stateless; instructs client to clear token
 * GET  /api/admin/me      → verify token (via requireAdmin middleware), return identity
 *
 * Dual-auth model:
 *   1. Custom JWT  — stored in sessionStorage on the client, used to authenticate
 *                    all backend API requests via requireAdmin middleware.
 *   2. Supabase session — returned after login so the frontend can call
 *                         supabase.auth.setSession(), which activates the admin's
 *                         Supabase identity (auth.uid() → admin UUID in profiles).
 *                         This makes is_admin() return true → RLS allows realtime
 *                         postgres_changes events to reach the AdminDashboard.
 *
 * IMPORTANT: Never expose hash, env vars, or stack traces in responses.
 */

import { validateAdminCredentials, signAdminToken } from '../services/adminAuthService.js'
import { supabaseAdmin } from '../config/supabase.js'

// ── POST /api/admin/login ──────────────────────────────────────────────────────
export async function adminLogin(req, res) {
  const { email, password } = req.body ?? {}

  // ── Basic validation ─────────────────────────────────────────────────────────
  if (!email || typeof email !== 'string' || email.trim().length === 0) {
    return res.status(400).json({ success: false, message: 'Email is required.' })
  }
  if (!password || typeof password !== 'string' || password.length === 0) {
    return res.status(400).json({ success: false, message: 'Password is required.' })
  }
  if (password.length > 256) {
    return res.status(400).json({ success: false, message: 'Invalid credentials.' })
  }

  try {
    // ── 1. Validate credentials via bcrypt (existing mechanism) ──────────────
    const admin = await validateAdminCredentials(email, password)

    // ── 2. Issue custom JWT ──────────────────────────────────────────────────
    const token = signAdminToken(admin.email)

    // ── 3. Get a Supabase session for the admin Supabase user ────────────────
    //   This session enables supabase.auth.setSession() on the frontend, so the
    //   frontend Supabase client gets an authenticated identity that satisfies
    //   is_admin() → RLS → realtime postgres_changes events flow correctly.
    //
    //   ADMIN_SUPABASE_PASSWORD is a server-only env var generated by the
    //   setup-admin-supabase-user.js script. It is NEVER sent to any client
    //   directly — only the resulting access_token + refresh_token are returned.
    let supabaseSession = null
    const supabaseAdminEmail    = process.env.ADMIN_EMAIL
    const supabaseAdminPassword = process.env.ADMIN_SUPABASE_PASSWORD

    if (supabaseAdminPassword) {
      const { data, error: sbError } = await supabaseAdmin.auth.signInWithPassword({
        email:    supabaseAdminEmail,
        password: supabaseAdminPassword,
      })
      if (sbError) {
        // Non-fatal: log and continue. Custom JWT still works; only realtime is affected.
        console.warn('[adminLogin] Supabase session creation failed (realtime will be degraded):', sbError.message)
      } else if (data?.session) {
        supabaseSession = {
          access_token:  data.session.access_token,
          refresh_token: data.session.refresh_token,
          expires_at:    data.session.expires_at,
        }
        console.info(`[adminLogin] Supabase session issued for admin ${admin.email}`)
      }
    } else {
      console.warn('[adminLogin] ADMIN_SUPABASE_PASSWORD not set — run scripts/setup-admin-supabase-user.js')
    }

    // ── 4. Respond ───────────────────────────────────────────────────────────
    return res.status(200).json({
      success:          true,
      token,
      admin:            { id: process.env.ADMIN_SUPABASE_UID, email: admin.email, role: 'admin' },
      supabase_session: supabaseSession,   // null if setup script hasn't been run
    })
  } catch (err) {
    // Generic error — never expose internal details
    console.error('[adminLogin] auth failure:', err.message)
    return res.status(401).json({
      success: false,
      message: 'Invalid credentials.',
    })
  }
}

// ── POST /api/admin/logout ─────────────────────────────────────────────────────
// Stateless JWT — the client is responsible for clearing the token.
export function adminLogout(req, res) {
  console.info(`[adminLogout] admin logged out: ${req.admin?.email ?? 'unknown'}`)
  return res.status(200).json({
    success: true,
    message: 'Logged out successfully.',
  })
}

// ── GET /api/admin/me ──────────────────────────────────────────────────────────
// requireAdmin middleware has already verified the JWT and attached req.admin.
export function adminMe(req, res) {
  return res.status(200).json({
    success: true,
    admin: {
      id:    process.env.ADMIN_SUPABASE_UID,
      email: req.admin.email,
      role:  req.admin.role,
    },
  })
}
